# Generated by Django 5.0.7 on 2024-07-13 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dir_app', '0002_explore_how_it_works_reviews_creator_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client_reviews',
            options={'verbose_name_plural': 'Client_reviews'},
        ),
        migrations.AlterModelOptions(
            name='how_it_works',
            options={'verbose_name_plural': 'How_it_works'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'Reviews'},
        ),
        migrations.RemoveField(
            model_name='creator',
            name='phone',
        ),
        migrations.CreateModel(
            name='About_web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_center', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dir_app.creator')),
            ],
            options={
                'verbose_name': 'About_web',
            },
        ),
    ]
