# Generated by Django 5.0.7 on 2024-07-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dir_app', '0003_alter_client_reviews_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_web',
            options={'verbose_name': 'About web'},
        ),
        migrations.AddField(
            model_name='explore',
            name='rated_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
