# Generated by Django 5.0.7 on 2024-07-13 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dir_app', '0004_alter_about_web_options_explore_rated_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='explore',
            name='posted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dir_app.creator'),
            preserve_default=False,
        ),
    ]
